version: 2

jobs:
  build:
    docker:
      - image: latupo/circleci-base
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t test .
      - run: docker run --rm test /bin/true
