version: 2

jobs:
  build:
    docker:
      - image: latupo/circleci-base
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t test .
      # Verify there is at least one volume binding
      - run: test $(docker inspect --format='{{len .Config.Volumes}}' test) -ge 1
      - run: docker run --rm test /bin/true
      - run: docker run --rm test supybot --version
      - run: docker run --rm test test '"$(whoami)" != "root"'
      - run: docker run --rm test touch boop
